### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by leawinner** [leawinner/tmp#3]

**Comment by leawinner** [comment]
Прох, посмотри примеры Wiki у других команд или то, что я тебе кидал и оформи Wiki на этом репозитории

**Comment by user-SteelRain** [comment]
Хай, я тут хреновенько сижу, наконец то скачал приложение. Всё ещё актуально? Займусь на досуге, если не актуально, то можно задание? А то такими темпами мы будем хрен знает сколько работать. Учитывая, что нас в принципе всего трое.

**Comment by leawinner** [comment]
в вики надо диаграмму классов добавить а это задача Азата @Mafilazat поэтому пока кайфуй
